language: java
jdk: oraclejdk8
branches:
  only: master
install: true
script: ".travis/build.sh"
after_success: ".travis/notify.sh Travis-Success"
after_failure: ".travis/notify.sh Travis-Failure"
env:
  global:
  - secure: U6ooHJf++vTblYaFJMcOML/yOwuCRigAh7D+m3vwvdHn/oirhP7FLtdZm8TZhW6P14Q/+NpmitS/waZthPfNOqturzFagPs+D9VZt7yW3bm1dUnQBrzit065iGuntGAF9dUINJpFfRf3AoUi2Ruf/tmn3xaO2YRDpqkVd+zYmPg=
  - secure: A/bVG5BKcFhzYWOrUkaqUcFeINPyYr04YcS5omB8I2zVelAsmB+i4QLtBOkvCpiyOkAUmQ3dZUe0Fd/SocirfAOpAoEY3crx/KDHmJvYUpXDIrHen1Lj8+6sw2wcVO61Rt2/Dr5o375t1jV2hQeW4Yv4eHftCnQuhT0FWHfobfg=
